# Generated by Django 4.2.15 on 2024-08-12 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.IntegerField(choices=[(0, '17:00'), (1, '17:30'), (2, '18:00'), (3, '18:30'), (4, '19:00'), (5, '19:30'), (6, '20:00'), (7, '20:30'), (8, '21:00'), (9, '21:30'), (10, '22:00'), (11, '22:30'), (12, '23:00')], default=0)),
                ('reservation_date', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='reservations.customer')),
            ],
            options={
                'ordering': ['-customer'],
            },
        ),
    ]
