# Generated by Django 4.2.15 on 2024-09-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=250)),
                ('review_date', models.DateField()),
                ('review_content', models.TextField()),
                ('reviewer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['review_date'],
            },
        ),
    ]
