# Generated by Django 4.2.15 on 2024-08-12 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='num_of_guests',
            new_name='number_of_guests',
        ),
        migrations.AlterField(
            model_name='table',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablessss', to='reservations.reservation'),
        ),
    ]
