# Generated by Django 4.2.15 on 2024-08-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_num_of_guests_reservation_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_id']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
