# Generated by Django 4.2.15 on 2024-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_feedback_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(max_length=250),
        ),
    ]
