# Generated by Django 4.2.15 on 2024-08-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_rename_first_name_customer_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='reservations.customer'),
        ),
    ]
